function [] = print(obj)
%cQuoteStock
    fprintf('%s trade:%s;bid:%s;ask:%s;instrument:%s;\n',obj.update_time2,...
        num2str(obj.last_trade),...
        num2str(obj.bid1),...
        num2str(obj.ask1),...
        obj.code_wind);
end