function res = getgreeks(obj,instrument)
    [flag,idx] = obj.options_.hasinstrument(instrument);
    if ~flag
        res = {};
        return
    end
    
    res = struct('delta',obj.delta_(idx),...
        'gamma',obj.gamma_(idx),...
        'vega',obj.vega_(idx),...
        'theta',obj.theta_(idx),...
        'impvol',obj.impvol_(idx),...
        'deltacarry',obj.deltacarry_(idx),...
        'gammacarry',obj.gammacarry_(idx),...
        'vegacarry',obj.vegacarry_(idx),...
        'thetcarry',obj.thetacarry_(idx),...
        'deltacarryyesterday',obj.deltacarryyesterday_(idx),...
        'gammacarryyesterday',obj.gammacarryyesterday_(idx),...
        'vegacarryyesterday',obj.vegacarryyesterday_(idx),...
        'thetacarryyesterday',obj.thetacarryyesterday_(idx),...
        'impvolcarryyesterday',obj.impvolcarryyesterday_(idx),...
        'pvcarryyesterday',obj.pvcarryyesterday_(idx));
end