%%
config = cStratConfigTDSQ;


%%
combo = rtt_setup('countername','ccb_ly_fut',...
    'bookname','booktdsq',...
    'strategyname','tdsq',...
    'tradesfilename','',...
    'riskconfigfilename','config_tdsq_standard_regressiontest.txt',...
    'initialfundlevel',1e6,...
    'usehistoricaldata',true);
