%test_CreateObj
%%
%user inputs
valuationDate = today;
currency = 'CNY';
assetName = 'gold';
vol = 0.12;
strike = 1;
spot = 1;
tenor = 30; %number of days

%%
%1.Create a yieldcurve object
myYC = CreateObj('myCurve','YIELDCURVE',...
                    'ValuationDate',today,'Currency',currency);
%%
%2.Create a mktdata object
myMktData = CreateObj('myMktData','MKTDATA',...
                      'ValuationDate',today,...
                      'AssetName',assetName,...
                      'Currency',currency,...
                      'Type','Forward',...
                      'Spot',spot);
%%
%3.Create a vol object
myVol = CreateObj('myVol','VOL',...
                  'VolName','MarketVol','VolType','StrikeVol',...
                  'AssetName',assetName,...
                  'Strikes',strike,...
                  'Expiries',valuationDate+tenor,...
                  'Vols',vol);             
 %%
 %4.Create a model object
 myModel = CreateObj('myModel','MODEL','ModelName','CCBSMC');
 %%
 %5.Create a security object
 myFutures = cContract('AssetName',assetName,'Tenor','1612');
 myOption = CreateObj('mySecurity','SECURITY',...
                        'SecurityName','EUROPEAN',...
                        'Strike',strike,...
                        'IssueDate',valuationDate,...
                        'ExpiryDate',valuationDate+tenor,...
                        'Underlier',myFutures,...
                        'OptionType','Call');
%%
%5.Create a dictionary
myDictionary = CreateObj('myDictionary','DICTIONARY',...
                        'YIELDCURVE',myYC,...
                        'MKTDATA',myMktData,...
                        'VOL',myVol,...
                        'MODEL',myModel,...
                        'SECURITY',myOption);
 
                    
                    
                    
                    