function [] = settimer(mytimerobj)
    timername = ['timer-',class(mytimerobj)];
    timertag = ['tag-',class(mytimerobj)];
    timertofind = timerfind('Name',timername);
    if isempty(mytimerobj.timer_) || isempty(timertofind)
        mytimerobj.timer_ = timer('Period', mytimerobj.timer_interval_,...
            'StartFcn',@mytimerobj.start_timer_fcn,...
            'TimerFcn', @mytimerobj.replay_timer_fcn,...
            'StopFcn',@mytimerobj.stop_timer_fcn,...
            'BusyMode', 'drop',...
            'ExecutionMode', 'fixedSpacing',...
            'StartDelay', min(mytimerobj.timer_interval_,5),...
            'Name',timername,...
            'Tag',timertag);
    end
end
%end of settimer