function [] = settimer(mytimerobj)
    mytimerobj.timer_ = timer('Period', mytimerobj.timer_interval_,...
        'StartFcn',@mytimerobj.start_timer_fcn,...
        'TimerFcn', @mytimerobj.replay_timer_fcn,...
        'StopFcn',@mytimerobj.stop_timer_fcn,...
        'BusyMode', 'drop',...
        'ExecutionMode', 'fixedSpacing',...
        'StartDelay', min(mytimerobj.timer_interval_,5));
end
%end of settimer