function handles = mygui_framework_mdefut()
%%
close all;
fgsz = [1, 1, 600, 600];
backcolor  = [1, 0.95, 0.85];
tbbackcolor = [0.8 1 0.8;0.6 1 1];
handles.output = figure('ToolBar', 'none', 'Menubar', 'none',...
    'Color', backcolor,'Position',fgsz);
set(handles.output, 'Name', 'Futures Market Data Engine', 'NumberTitle', 'off');
movegui(handles.output, 'north')
parent = handles.output;

% counter
% position [left bottom width height]
handles.counter.panelbox = uipanel('Parent', parent, 'Title', 'Counter', ...
    'Units', 'Normalized', 'Position', [0.05 0.88 0.2 0.1],'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'lefttop');
panelbox = handles.counter.panelbox;
handles.counter.popup_counter = uicontrol('Parent', panelbox, 'style', 'popupmenu', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'w', 'String', {'citic_kim_fut','ccb_ly_fut'}, ...
    'Units', 'Normalized', 'Position', [0.05 0.8 0.9 0.05], 'FontSize', 9, ...
    'FontWeight', 'bold');

% instruments
handles.instruments.panelbox = uipanel('Parent', parent, 'Title', 'Instruments', ...
    'Units', 'Normalized', 'Position', [0.05 0.3 0.9 0.52], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'lefttop');
panelbox = handles.instruments.panelbox;
handles.instruments.table  = uitable('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.025 0.01 0.95 0.98], 'FontSize' , 9 , 'FontWeight' ,'bold', ...
    'Data', num2cell(ones(13, 5)*NaN), 'ColumnWidth', num2cell(ones(1,5)*80), 'BackgroundColor', tbbackcolor,...
    'RowName',{'cu1811','al1811','zn1811','pb1811','ni1811','rb1901','i1901','m1901','SR901','IF1809','IH1809','IC1809','T1812'},...
    'ColumnName',{'bid size','bid','ask','ask size','update time'});

% operation
handles.operation.panelbox = uipanel('Parent', parent, 'Title', 'Operation', ...
    'Units', 'Normalized', 'Position', [0.05 0.2 0.2 0.075], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'lefttop');
panelbox = handles.operation.panelbox;
handles.operation.button_futquote   = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', 'market quotes', ...
    'Units', 'Normalized', 'Position', [0.03 0.06 0.88 0.94], 'FontSize', 9, ...
    'FontWeight', 'bold');
