strat = cStratManual;
shfe_ctp_codes = {'cu1811';'al1811';'zn1811';'pb1811';'ni1811';'rb1901'};
mdefut = cMDEFut;

strat.registermdefut(mdefut);
for i = 1:size(shfe_ctp_codes,1)
    strat.registerinstrument(shfe_ctp_codes{i});
end

clc;
fprintf('strategy default setup basic information:\n');
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','code',shfe_ctp_codes{1},shfe_ctp_codes{2},shfe_ctp_codes{3},shfe_ctp_codes{4},shfe_ctp_codes{5},shfe_ctp_codes{6});
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','stoptype',...
    strat.getstoptype(shfe_ctp_codes{1}),...
    strat.getstoptype(shfe_ctp_codes{2}),...
    strat.getstoptype(shfe_ctp_codes{3}),...
    strat.getstoptype(shfe_ctp_codes{4}),...
    strat.getstoptype(shfe_ctp_codes{5}),...
    strat.getstoptype(shfe_ctp_codes{6}));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','stopamount',...
    num2str(strat.getstopamount(shfe_ctp_codes{1})),...
    num2str(strat.getstopamount(shfe_ctp_codes{2})),...
    num2str(strat.getstopamount(shfe_ctp_codes{3})),...
    num2str(strat.getstopamount(shfe_ctp_codes{4})),...
    num2str(strat.getstopamount(shfe_ctp_codes{5})),...
    num2str(strat.getstopamount(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','limittype',...
    strat.getlimittype(shfe_ctp_codes{1}),...
    strat.getlimittype(shfe_ctp_codes{2}),...
    strat.getlimittype(shfe_ctp_codes{3}),...
    strat.getlimittype(shfe_ctp_codes{4}),...
    strat.getlimittype(shfe_ctp_codes{5}),...
    strat.getlimittype(shfe_ctp_codes{6}));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','limitamount',...
    num2str(strat.getlimitamount(shfe_ctp_codes{1})),...
    num2str(strat.getlimitamount(shfe_ctp_codes{2})),...
    num2str(strat.getlimitamount(shfe_ctp_codes{3})),...
    num2str(strat.getlimitamount(shfe_ctp_codes{4})),...
    num2str(strat.getlimitamount(shfe_ctp_codes{5})),...
    num2str(strat.getlimitamount(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','bidopenspread',...
    num2str(strat.getbidopenspread(shfe_ctp_codes{1})),...
    num2str(strat.getbidopenspread(shfe_ctp_codes{2})),...
    num2str(strat.getbidopenspread(shfe_ctp_codes{3})),...
    num2str(strat.getbidopenspread(shfe_ctp_codes{4})),...
    num2str(strat.getbidopenspread(shfe_ctp_codes{5})),...
    num2str(strat.getbidopenspread(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','bidclosespread',...
    num2str(strat.getbidclosespread(shfe_ctp_codes{1})),...
    num2str(strat.getbidclosespread(shfe_ctp_codes{2})),...
    num2str(strat.getbidclosespread(shfe_ctp_codes{3})),...
    num2str(strat.getbidclosespread(shfe_ctp_codes{4})),...
    num2str(strat.getbidclosespread(shfe_ctp_codes{5})),...
    num2str(strat.getbidclosespread(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','askopenspread',...
    num2str(strat.getaskopenspread(shfe_ctp_codes{1})),...
    num2str(strat.getaskopenspread(shfe_ctp_codes{2})),...
    num2str(strat.getaskopenspread(shfe_ctp_codes{3})),...
    num2str(strat.getaskopenspread(shfe_ctp_codes{4})),...
    num2str(strat.getaskopenspread(shfe_ctp_codes{5})),...
    num2str(strat.getaskopenspread(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','askclosespread',...
    num2str(strat.getaskclosespread(shfe_ctp_codes{1})),...
    num2str(strat.getaskclosespread(shfe_ctp_codes{2})),...
    num2str(strat.getaskclosespread(shfe_ctp_codes{3})),...
    num2str(strat.getaskclosespread(shfe_ctp_codes{4})),...
    num2str(strat.getaskclosespread(shfe_ctp_codes{5})),...
    num2str(strat.getaskclosespread(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','baseunits',...
    num2str(strat.getbaseunits(shfe_ctp_codes{1})),...
    num2str(strat.getbaseunits(shfe_ctp_codes{2})),...
    num2str(strat.getbaseunits(shfe_ctp_codes{3})),...
    num2str(strat.getbaseunits(shfe_ctp_codes{4})),...
    num2str(strat.getbaseunits(shfe_ctp_codes{5})),...
    num2str(strat.getbaseunits(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','maxunits',...
    num2str(strat.getmaxunits(shfe_ctp_codes{1})),...
    num2str(strat.getmaxunits(shfe_ctp_codes{2})),...
    num2str(strat.getmaxunits(shfe_ctp_codes{3})),...
    num2str(strat.getmaxunits(shfe_ctp_codes{4})),...
    num2str(strat.getmaxunits(shfe_ctp_codes{5})),...
    num2str(strat.getmaxunits(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','autotrade',...
    num2str(strat.getautotradeflag(shfe_ctp_codes{1})),...
    num2str(strat.getautotradeflag(shfe_ctp_codes{2})),...
    num2str(strat.getautotradeflag(shfe_ctp_codes{3})),...
    num2str(strat.getautotradeflag(shfe_ctp_codes{4})),...
    num2str(strat.getautotradeflag(shfe_ctp_codes{5})),...
    num2str(strat.getautotradeflag(shfe_ctp_codes{6})));
%
fprintf('%25s%10s%10s%10s%10s%10s%10s\n','maxexecutionperbucket',...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{1})),...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{2})),...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{3})),...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{4})),...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{5})),...
    num2str(strat.getmaxexecutionperbucket(shfe_ctp_codes{6})));

% strategy default setup basic information:
%                      code    cu1811    al1811    zn1811    pb1811    ni1811    rb1901
%                  stoptype       rel       rel       rel       rel       rel       rel
%                stopamount      -Inf      -Inf      -Inf      -Inf      -Inf      -Inf
%                 limittype       rel       rel       rel       rel       rel       rel
%               limitamount       Inf       Inf       Inf       Inf       Inf       Inf
%             bidopenspread         0         0         0         0         0         0
%            bidclosespread         0         0         0         0         0         0
%             askopenspread         0         0         0         0         0         0
%            askclosespread         0         0         0         0         0         0
%                 baseunits         1         1         1         1         1         1
%                  maxunits         1         1         1         1         1         1
%                 autotrade         0         0         0         0         0         0
%     maxexecutionperbucket         1         1         1         1         1         1
