function [] = settimer(strategy)
    if strcmpi(strategy.mode_, 'debug')
        strategy.timer_interval_ = 0.005;
    end

    strategy.timer_ = timer('Period', strategy.timer_interval_,...
        'StartFcn',@strategy.start_timer_fcn,...
        'TimerFcn', @strategy.replay_timer_fcn,...
        'StopFcn',@strategy.stop_timer_fcn,...
        'BusyMode', 'drop',...
        'ExecutionMode', 'fixedSpacing',...
        'StartDelay', min(strategy.timer_interval_,5));

end