asset = 'glass';
dtfrom = '2024-05-06';
[tblout,kellyout,tblout_notused] = charlotte_kellycheck('assetname',asset,...
    'datefrom',dtfrom,...
    'frequency','intraday',...
    'reportunused',true);
open tblout;
open kellyout;
open tblout_notused;
%%
[tblpnl,tblout2,statsout] = charlotte_gensingleassetprofile('assetname',asset);
open tblout2;
open statsout;
timeseries_plot([tblpnl.dts,tblpnl.runningnotional],'figureindex',2,'dateformat','yy-mmm-dd','title',asset);
%%
code = tblout2.code{end};
[tblb_headers,tblb_data,~,tbls_data,data] = fractal_gettradesummary(code,...
    'frequency','intraday',...
    'usefractalupdate',0,...
    'usefibonacci',1,...
    'direction','both');