[~,~,codes_index,codes_sector] = isinequitypool('');
nindex = size(codes_index,1);
nsector = size(codes_sector,1);
names_etf_index = cell(nindex,1);
names_etf_sector = cell(nsector,1);
resstruct_etf_index = cell(nindex,1);
resstruct_etf_sector = cell(nsector,1);
for i = 1:nindex
    etf_i = code2instrument(codes_index{i});
    names_etf_index{i} = etf_i.asset_name;
    resstruct_etf_index{i} = charlotte_plot('futcode',codes_index{i},'datefrom','2024-10-01','frequency','daily','doplot',false);
    if nindex > 0 && i == 1
        fprintf('ETF index daily report......\n');
        fprintf('\t%8s\t%12s\t%10s\t%10s\t%10s\t%10s\t\t%s\n','CODE','DATE','CLOSE','CHG','UPPER','LOWER','NAME');
    end
    fprintf('\t%8s\t%12s\t%10s\t%9.1f%%\t%10s\t%10s\t\t%s\n',codes_index{i},...
        datestr(resstruct_etf_index{i}.px(end,1),'yyyy-mm-dd'),...
        num2str(resstruct_etf_index{i}.px(end,5)),...
        100*(resstruct_etf_index{i}.px(end,5)/resstruct_etf_index{i}.px(end-1,5)-1),...
        num2str(resstruct_etf_index{i}.hh(end)),...
        num2str(resstruct_etf_index{i}.ll(end)),...
        names_etf_index{i});
end
%
dir_ = [getenv('onedrive'),'\fractal backtest\kelly distribution\matlab\etfs\'];
fn_ = 'strat_daily_etfs.mat';
data_ = load([dir_,fn_]);
kellytables = data_.strat_daily_etfs;
uts = cell(nindex,1);
cts = cell(nindex,1);
tbls = cell(nindex,1);
for i = 1:nindex
    dt2 = datestr(resstruct_etf_index{i}.px(end,1),'yyyy-mm-dd');
    [uts{i},cts{i},tbls{i}] = charlotte_backtest_period('code',codes_index{i},...
        'fromdate','2024-12-01',...
        'todate',dt2,...
        'kellytables',kellytables,'showlogs',false,'figureidx',i+1,'frequency','daily');
    
    charlotte_backtest_period('code',codes_index{i},...
        'fromdate',dt2,...
        'todate',dt2,...
        'kellytables',kellytables,'showlogs',true,'figureidx',i+1,'frequency','daily','doplot',false);
end
%
fprintf('\n')
ncount = 0;
for i = 1:nindex
    if cts{i}.latest_ > 0
        ncount = ncount + 1;
        if ncount == 1
            fprintf('\t%6s\t%3s\t%12s\t%10s\t%10s\t%30s\t%9s\t%9s\n',...
                'Code',...
                'B/S',...
                'OpenDt',...
                'OpenPx',...
                'Latest',...
                'OpenSignal',...
                'OpenKelly',...
                'Stoploss');
        end
        t_i = cts{i}.node_(1);
        fprintf('\t%6s\t%3d\t%12s\t%10s\t%10s\t%30s\t%8.1f%%\t%8.4f\n',codes_index{i},t_i.opendirection_,...
            datestr(t_i.opendatetime1_,'yyyy-mm-dd'),num2str(t_i.openprice_),num2str(resstruct_etf_index{i}.px(end,5)),...
            t_i.opensignal_.mode_,100*t_i.opensignal_.kelly_,...
            t_i.riskmanager_.pxstoploss_);
    end
end
%%
for i = 1:nsector
    etf_i = code2instrument(codes_sector{i});
    names_etf_sector{i} = etf_i.asset_name;
    resstruct_etf_sector{i} = charlotte_plot('futcode',codes_sector{i},'datefrom','2024-10-01','frequency','daily','doplot',false);
    if nsector > 0 && i == 1
        fprintf('\nETF sector daily report......\n');
        fprintf('\t%8s\t%12s\t%10s\t%10s\t%10s\t%10s\t\t%s\n','CODE','DATE','CLOSE','CHG','UPPER','LOWER','NAME');
    end
    fprintf('\t%8s\t%12s\t%10s\t%9.1f%%\t%10s\t%10s\t\t%s\n',codes_sector{i},...
        datestr(resstruct_etf_sector{i}.px(end,1),'yyyy-mm-dd'),...
        num2str(resstruct_etf_sector{i}.px(end,5)),...
        100*(resstruct_etf_sector{i}.px(end,5)/resstruct_etf_sector{i}.px(end-1,5)-1),...
        num2str(resstruct_etf_sector{i}.hh(end)),...
        num2str(resstruct_etf_sector{i}.ll(end)),...
        names_etf_sector{i});
end
uts2 = cell(nsector,1);
cts2 = cell(nsector,1);
tbls2 = cell(nsector,1);
for i = 1:nsector
    dt2 = datestr(resstruct_etf_sector{i}.px(end,1),'yyyy-mm-dd');
    [uts2{i},cts2{i},tbls2{i}] = charlotte_backtest_period('code',codes_sector{i},...
        'fromdate','2024-12-01',...
        'todate',dt2,...
        'kellytables',kellytables,'showlogs',false,'figureidx',i+1,'frequency','daily');
    
    charlotte_backtest_period('code',codes_sector{i},...
        'fromdate',dt2,...
        'todate',dt2,...
        'kellytables',kellytables,'showlogs',true,'figureidx',i+1,'frequency','daily','doplot',false);
end
%
fprintf('\n')
ncount = 0;
for i = 1:nsector
    if cts2{i}.latest_ > 0
        ncount = ncount + 1;
        if ncount == 1
            fprintf('\t%6s\t%3s\t%12s\t%10s\t%10s\t%30s\t%9s\t%9s\n',...
                'Code',...
                'B/S',...
                'OpenDt',...
                'OpenPx',...
                'Latest',...
                'OpenSignal',...
                'OpenKelly',...
                'Stoploss');
        end
        t_i = cts2{i}.node_(1);
        fprintf('\t%6s\t%3d\t%12s\t%10s\t%10s\t%30s\t%8.1f%%\t%8.4f\n',codes_sector{i},t_i.opendirection_,...
            datestr(t_i.opendatetime1_,'yyyy-mm-dd'),num2str(t_i.openprice_),num2str(resstruct_etf_sector{i}.px(end,5)),...
            t_i.opensignal_.mode_,100*t_i.opensignal_.kelly_,...
            t_i.riskmanager_.pxstoploss_);
    end
end
%%
[ut_,ct_,tbls_] = charlotte_backtest_period('code','159995',...
        'fromdate','2025-01-01',...
        'todate',dt2,...
        'kellytables',kellytables,'showlogs',true,'figureidx',i+1,'frequency','daily');