function selected = charlotte_select_fx_pairs()
%     selected = {'EURUSD.lmx';...
%                 'GBPUSD.lmx';...
%                 'USDJPY.lmx';...
%                 'USDCHF.lmx';...
%                 'USDCAD.lmx';...
%                 'AUDUSD.lmx';...
%                 'EURGBP.lmx';...
%                 'XAUUSD.lmx';...
%                 'XAGUSD.lmx'};
    selected = {'EURUSD';...
                'GBPUSD';...
                'USDJPY';...
                'USDCHF';...
                'USDCAD';...
                'AUDUSD';...
                'XAUUSD'};        
            
end