function [] = startat(mdefut,dtstr)
    mdefut.status_ = 'working';
    mdefut.timer_ = timer('Period', mdefut.timer_interval_,...
        'StartFcn',@mdefut.start_timer_fcn,...
        'TimerFcn', @mdefut.replay_timer_fcn,...
        'StopFcn',@mdefut.stop_timer_fcn,...
        'BusyMode', 'drop',...
        'ExecutionMode', 'fixedSpacing',...
        'StartDelay', min(mdefut.timer_interval_,5));
    y = year(dtstr);
    m = month(dtstr);
    d = day(dtstr);
    hh = hour(dtstr);
    mm = minute(dtstr);
    ss = second(dtstr);
    startat(mdefut.timer_,y,m,d,hh,mm,ss);
end
%end of startat