function [] = start(mdefut)
    mdefut.status_ = 'working';
    mdefut.timer_ = timer('Period', mdefut.timer_interval_,...
        'StartFcn',@mdefut.start_timer_fcn,...
        'TimerFcn', @mdefut.replay_timer_fcn,...
        'StopFcn',@mdefut.stop_timer_fcn,...
        'BusyMode', 'drop',...
        'ExecutionMode', 'fixedSpacing',...
        'StartDelay', min(mdefut.timer_interval_,5));
    start(mdefut.timer_);
end
%end of start