function [ret] = fractal_isvalidstr(filterstr)
    ret = false;
    if strcmpi(filterstr,'breachup-lvlup') || ...
            strcmpi(filterstr,'breachup-lvldn') || ...
            strcmpi(filterstr,'breachup-highsc13') || ...
            strcmpi(filterstr,'breachup-highsc13-negative') || ...
            strcmpi(filterstr,'breachup-sshighvalue') ||...
            strcmpi(filterstr,'breachdn-lvldn') || ...
            strcmpi(filterstr,'breachdn-lvlup') || ...
            strcmpi(filterstr,'breachdn-lowbc13') || ...
            strcmpi(filterstr,'breachdn-lowbc13-positive') || ...
            strcmpi(filterstr,'breachdn-bshighvalue') ||...
            strcmpi(filterstr,'volblowup') || ...
            strcmpi(filterstr,'volblowup-alligatorfailed') || ...
            strcmpi(filterstr,'volblowup2') || ...    
            strcmpi(filterstr,'volblowup2-alligatorfailed') || ...
            strcmpi(filterstr,'volblowup2-ss1') || ...
            strcmpi(filterstr,'volblowup2-bs1') || ...
            strcmpi(filterstr,'strongbreach-trendbreak') ||...
            strcmpi(filterstr,'strongbreach-trendbreak-s') ||...
            strcmpi(filterstr,'strongbreach-trendconfirmed') ||...
            strcmpi(filterstr,'strongbreach-sshighvalue') ||...
            strcmpi(filterstr,'strongbreach-bshighvalue') ||...
            strcmpi(filterstr,'mediumbreach-trendbreak') ||...
            strcmpi(filterstr,'mediumbreach-trendbreak-s') ||...
            strcmpi(filterstr,'mediumbreach-trendbreak-s1') ||...
            strcmpi(filterstr,'mediumbreach-trendbreak-bsreverse') ||...
            strcmpi(filterstr,'mediumbreach-trendbreak-bsbcdoublereverse') ||...
            strcmpi(filterstr,'mediumbreach-trendconfirmed') ||...
            strcmpi(filterstr,'mediumbreach-sshighvalue') ||...
            strcmpi(filterstr,'mediumbreach-bshighvalue') ||...
            strcmpi(filterstr,'teethjawcrossed') || ...
            strcmpi(filterstr,'closetolvlup') ||...
            strcmpi(filterstr,'closetolvldn') ||...
            strcmpi(filterstr,'weakbreach') || ...
            strcmpi(filterstr,'sc13') || ...
            strcmpi(filterstr,'bc13')
        ret = true;
    end


end