function res = fractal_truncate(extrainfo,breachidx,startidx)
if nargin < 3
    startidx = 1;
end
if isstruct(extrainfo)
    res = struct('px',extrainfo.px(startidx:breachidx,:),...
        'ss',extrainfo.ss(startidx:breachidx),...
        'sc',extrainfo.sc(startidx:breachidx),...
        'bs',extrainfo.bs(startidx:breachidx),...
        'bc',extrainfo.bc(startidx:breachidx),...
        'idxhh',extrainfo.idxhh(startidx:breachidx),...
        'idxll',extrainfo.idxll(startidx:breachidx),...
        'lvlup',extrainfo.lvlup(startidx:breachidx),...
        'lvldn',extrainfo.lvldn(startidx:breachidx),...
        'hh',extrainfo.hh(startidx:breachidx),...
        'll',extrainfo.ll(startidx:breachidx),...
        'lips',extrainfo.lips(startidx:breachidx),...
        'teeth',extrainfo.teeth(startidx:breachidx),...
        'jaw',extrainfo.jaw(startidx:breachidx),...
        'wad',extrainfo.wad(startidx:breachidx));
else
    error('fractal_truncate:struct input missing......')
end