function extrainfo = fractal_genextrainfo(resstruct,idx)
    j = idx;
    extrainfo = struct('px',resstruct.px(1:j,:),...
        'bs',resstruct.bs(1:j),'ss',resstruct.ss(1:j),...
        'bc',resstruct.bc(1:j),'sc',resstruct.sc(1:j),...
        'lvlup',resstruct.lvlup(1:j),'lvldn',resstruct.lvldn(1:j),...
        'idxhh',resstruct.idxhh(1:j),'hh',resstruct.hh(1:j),...
        'idxll',resstruct.idxll(1:j),'ll',resstruct.ll(1:j),...
        'lips',resstruct.lips(1:j),'teeth',resstruct.teeth(1:j),'jaw',resstruct.jaw(1:j),...
        'wad',resstruct.wad(1:j),...
        'p',resstruct.px(1:j,:));
end