function [] = exporttrade2mt4(trade,fn,permission)
% utility function to export trade (a cTradeOpen instance) information to a
% txt file (fn), which can be read to MT4
% fn = [getenv('APPDATA'),'\MetaQuotes\Terminal\Common\Files\matlab_trades.txt'];

    fid = fopen(fn,permission);
    fprintf(fid,'%s\t%2d\t%4.3f\t%4.3f\t%s\t%s\n',trade.code_,...
        trade.opendirection_,...
        trade.openprice_,...
        trade.riskmanager_.pxstoploss_,...
        datestr(trade.opendatetime1_,'yyyy.mm.dd HH:MM'),...
        trade.opensignal_.mode_);
    
    fclose(fid);
end