function [flag] = isfx(asset)
    if ~ischar(asset)
        error('isfx:invalid asset input, a string is expected...')
    end
    
    fn_fx = {'usdx';...
        'eurusd';'eurusd.lmx';...
        'usdjpy';'usdjpy.lmx';...
        'gbpusd';'gbpusd.lmx';...
        'audusd';'audusd.lmx';...
        'usdcad';'usdcad.lmx';...
        'usdchf';'usdchf.lmx';...
        'eurjpy';'eurjpy.lmx';...
        'eurchf';'eurchf.lmx';...
        'gbpeur';'gbpeur.lmx';...
        'gbpjpy';'gbpjpy.lmx';...
        'audjpy';'audjpy.lmx';...
        'usdcnh';'usdcnh.lmx';...
        'xauusd';'xauusd.lmx';...
        'xagusd';'xagusd.lmx';...
    };
    
    if sum(strcmpi(asset,fn_fx)) > 0
        flag = true;
    else
        flag = false;
    end
end