%%
codes_ag = {
    'ag2006';'ag2012';...
    'ag2102';'ag2106';'ag2112';...
    'ag2206';'ag2212';...
    'ag2302';'ag2306';'ag2308';'ag2310';'ag2312';...
    'ag2402';...
    };
%
codes_au = {
    'au2006';'au2012';...
    'au2102';'au2106';'au2112';...
    'au2202';'au2206';'au2212';...
    'au2302';'au2304';'au2306';'au2308';'au2310';'au2312';...
    'au2402';...
    };
%
output_preciousmetal = fractal_kelly_summary('codes',[codes_ag;codes_au],'frequency','intraday','usefractalupdate',0,'usefibonacci',1,'direction','both');
%%
[tc_preciousmetal_i,tb_preciousmetal_i,tbl_preciousmetal_i,k_l_preciousmetal_i,k_s_preciousmetal_i,tblbyasset_l_preciousmetal_i,tblbyasset_s_preciousmetal_i] = kellydistrubitionsummary(output_preciousmetal);
%%
signal_l_valid_preciousmetal = k_l_preciousmetal_i.opensignal_unique_l(logical(k_l_preciousmetal_i.use_unique_l));
signal_s_valid_preciousmetal = k_s_preciousmetal_i.opensignal_unique_s(logical(k_s_preciousmetal_i.use_unique_s));
assetlist_preciousmetal = unique([tblbyasset_l_preciousmetal_i.assetlist;tblbyasset_s_preciousmetal_i.assetlist]);
nasset = size(assetlist_preciousmetal,1);
%
WMat_L_preciousmetal_i = zeros(length(signal_l_valid_preciousmetal),nasset);
RMat_L_preciousmetal_i = WMat_L_preciousmetal_i;
KMat_L_preciousmetal_i = WMat_L_preciousmetal_i;
for i = 1:length(signal_l_valid_preciousmetal)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_preciousmetal,'assetname',assetlist_preciousmetal{j},'direction','l','signalname',signal_l_valid_preciousmetal{i});
        WMat_L_preciousmetal_i(i,j) = ret.W;
        RMat_L_preciousmetal_i(i,j) = ret.R;
        KMat_L_preciousmetal_i(i,j) = ret.K;
    end
end
%
WMat_S_preciousmetal_i = zeros(length(signal_s_valid_preciousmetal),nasset);
RMat_S_preciousmetal_i = WMat_S_preciousmetal_i;
KMat_S_preciousmetal_i = WMat_S_preciousmetal_i;
for i = 1:length(signal_s_valid_preciousmetal)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_preciousmetal,'assetname',assetlist_preciousmetal{j},'direction','s','signalname',signal_s_valid_preciousmetal{i});
        WMat_S_preciousmetal_i(i,j) = ret.W;
        RMat_S_preciousmetal_i(i,j) = ret.R;
        KMat_S_preciousmetal_i(i,j) = ret.K;
    end
end
%
%%
strat_intraday_preciousmetal = struct('tblbyasset_l',tblbyasset_l_preciousmetal_i,...
    'tblbyasset_s',tblbyasset_s_preciousmetal_i,...
    'kelly_table_l',k_l_preciousmetal_i,...
    'kelly_table_s',k_s_preciousmetal_i,...
    tc_preciousmetal_i{1}.name,tc_preciousmetal_i{1}.table,...
    tc_preciousmetal_i{2}.name,tc_preciousmetal_i{2}.table,...
    tc_preciousmetal_i{3}.name,tc_preciousmetal_i{3}.table,...
    tc_preciousmetal_i{4}.name,tc_preciousmetal_i{4}.table,...
    'breachuplvlup_tb',tb_preciousmetal_i{1}.table,...
    'breachdnlvldn_tb',tb_preciousmetal_i{2}.table,...
    'breachupsshighvalue_tb',tb_preciousmetal_i{3}.table,...
    'breachdnbshighvalue_tb',tb_preciousmetal_i{4}.table,...
    'breachuplvlup_tc',tc_preciousmetal_i{5}.table,...
    'breachdnlvldn_tc',tc_preciousmetal_i{6}.table,...
    'breachupsshighvalue_tc',tc_preciousmetal_i{7}.table,...
    'breachdnbshighvalue_tc',tc_preciousmetal_i{8}.table,...
    'breachuphighsc13',tc_preciousmetal_i{9}.table,...
    'breachdnlowbc13',tc_preciousmetal_i{10}.table,...
    'kelly_matrix_l',KMat_L_preciousmetal_i,...
    'kelly_matrix_s',KMat_S_preciousmetal_i,...
    'winprob_matrix_l',WMat_L_preciousmetal_i,...
    'winprob_matrix_s',WMat_S_preciousmetal_i,...
    'signal_l',{signal_l_valid_preciousmetal},...
    'signal_s',{signal_s_valid_preciousmetal},...
    'asset_list',{assetlist_preciousmetal'});
%%
dir_ = [getenv('onedrive'),'\fractal backtest\kelly distribution\matlab\preciousmetal\'];
save([dir_,'strat_intraday_preciousmetal.mat'],'strat_intraday_preciousmetal');
fprintf('file saved...\n');
