codes_oi = {'OI901';'OI905';'OI909';'OI101';'OI105';'OI109';...
    'OI201';'OI205';'OI209';...
    'OI301';'OI305';'OI309';...
    'OI401'};
%
codes_p = {'p1901';'p1905';'p1909';'p2001';'p2005';'p2009';...
    'p2101';'p2105';'p2109';'p2201';'p2205';'p2209';...
    'p2301';'p2305';'p2309';...
    'p2401'};
%
codes_y = {'y1901';'y1905';'y1909';'y2001';'y2005';'y2009';...
    'y2101';'y2105';'y2109';'y2201';'y2205';'y2209';...
    'y2301';'y2305';'y2309';...
    'y2401'};
%
codes_grease = [codes_oi;codes_p;codes_y];
output_grease = fractal_kelly_summary('codes',codes_grease,'frequency','intraday','usefractalupdate',0,'usefibonacci',1,'direction','both');
%%
[tc_grease_i,tb_grease_i,tbl_grease_i,k_l_grease_i,k_s_grease_i,tblbyasset_l_grease_i,tblbyasset_s_grease_i] = kellydistrubitionsummary(output_grease);
%%
signal_l_valid_grease = k_l_grease_i.opensignal_unique_l(logical(k_l_grease_i.use_unique_l));
signal_s_valid_grease = k_s_grease_i.opensignal_unique_s(logical(k_s_grease_i.use_unique_s));
assetlist_grease = unique([tblbyasset_l_grease_i.assetlist;tblbyasset_s_grease_i.assetlist]);
nasset = size(assetlist_grease,1);
%
WMat_L_grease_i = zeros(length(signal_l_valid_grease),nasset);
RMat_L_grease_i = WMat_L_grease_i;
KMat_L_grease_i = WMat_L_grease_i;
for i = 1:length(signal_l_valid_grease)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_grease,'assetname',assetlist_grease{j},'direction','l','signalname',signal_l_valid_grease{i});
        WMat_L_grease_i(i,j) = ret.W;
        RMat_L_grease_i(i,j) = ret.R;
        KMat_L_grease_i(i,j) = ret.K;
    end
end
%
WMat_S_grease_i = zeros(length(signal_s_valid_grease),nasset);
RMat_S_grease_i = WMat_S_grease_i;
KMat_S_grease_i = WMat_S_grease_i;
for i = 1:length(signal_s_valid_grease)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_grease,'assetname',assetlist_grease{j},'direction','s','signalname',signal_s_valid_grease{i});
        WMat_S_grease_i(i,j) = ret.W;
        RMat_S_grease_i(i,j) = ret.R;
        KMat_S_grease_i(i,j) = ret.K;
    end
end
%
%%
strat_daily_grease = struct('tblbyasset_l',tblbyasset_l_grease_i,...
    'tblbyasset_s',tblbyasset_s_grease_i,...
    'kelly_tbl_l',k_l_grease_i,...
    'kelly_tbl_s',k_s_grease_i,...
    tc_grease_i{1}.name,tc_grease_i{1}.table,...
    tc_grease_i{2}.name,tc_grease_i{2}.table,...
    tc_grease_i{3}.name,tc_grease_i{3}.table,...
    tc_grease_i{4}.name,tc_grease_i{4}.table,...
    'breachuplvlup_tb',tb_grease_i{1}.table,...
    'breachdnlvldn_tb',tb_grease_i{2}.table,...
    'breachupsshighvalue_tb',tb_grease_i{3}.table,...
    'breachdnbshighvalue_tb',tb_grease_i{4}.table,...
    'kelly_matrix_l',KMat_L_grease_i,...
    'kelly_matrix_s',WMat_S_grease_i,...
    'signal_l',{signal_l_valid_grease},...
    'signal_s',{signal_s_valid_grease},...
    'asset_list',{assetlist_grease'});
