%
codes_T = {'T1706';'T1709';'T1712';...
    'T1803';'T1806';'T1809';'T1812';...
    'T1903';'T1906';'T1909';'T1912';...
    'T2003';'T2006';'T2009';'T2012';...
    'T2103';'T2106';'T2109';'T2112';...
    'T2203';'T2206';'T2209';'T2212';...
    'T2303';'T2306';'T2309';'T2312';...
    };
%
output_govtbondfut = fractal_kelly_summary('codes',codes_T,'frequency','intraday','usefractalupdate',0,'usefibonacci',1,'direction','both');
%%
[tc_govtbondfut_i,tb_govtbondfut_i,tbl_govtbondfut_i,k_l_govtbondfut_i,k_s_govtbondfut_i,tblbyasset_l_govtbondfut_i,tblbyasset_s_govtbondfut_i] = kellydistrubitionsummary(output_govtbondfut);
%%
signal_l_valid_govtbondfut = k_l_govtbondfut_i.opensignal_unique_l(logical(k_l_govtbondfut_i.use_unique_l));
signal_s_valid_govtbondfut = k_s_govtbondfut_i.opensignal_unique_s(logical(k_s_govtbondfut_i.use_unique_s));
assetlist_govtbondfut = unique([tblbyasset_l_govtbondfut_i.assetlist;tblbyasset_s_govtbondfut_i.assetlist]);
nasset = size(assetlist_govtbondfut,1);
%
WMat_L_govtbondfut_i = zeros(length(signal_l_valid_govtbondfut),nasset);
RMat_L_govtbondfut_i = WMat_L_govtbondfut_i;
KMat_L_govtbondfut_i = WMat_L_govtbondfut_i;
for i = 1:length(signal_l_valid_govtbondfut)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_govtbondfut,'assetname',assetlist_govtbondfut{j},'direction','l','signalname',signal_l_valid_govtbondfut{i});
        WMat_L_govtbondfut_i(i,j) = ret.W;
        RMat_L_govtbondfut_i(i,j) = ret.R;
        KMat_L_govtbondfut_i(i,j) = ret.K;
    end
end
%
WMat_S_govtbondfut_i = zeros(length(signal_s_valid_govtbondfut),nasset);
RMat_S_govtbondfut_i = WMat_S_govtbondfut_i;
KMat_S_govtbondfut_i = WMat_S_govtbondfut_i;
for i = 1:length(signal_s_valid_govtbondfut)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_govtbondfut,'assetname',assetlist_govtbondfut{j},'direction','s','signalname',signal_s_valid_govtbondfut{i});
        WMat_S_govtbondfut_i(i,j) = ret.W;
        RMat_S_govtbondfut_i(i,j) = ret.R;
        KMat_S_govtbondfut_i(i,j) = ret.K;
    end
end
%
%%
strat_intraday_govtbondfut = struct('tblbyasset_l',tblbyasset_l_govtbondfut_i,...
    'tblbyasset_s',tblbyasset_s_govtbondfut_i,...
    'kelly_table_l',k_l_govtbondfut_i,...
    'kelly_table_s',k_s_govtbondfut_i,...
    tc_govtbondfut_i{1}.name,tc_govtbondfut_i{1}.table,...
    tc_govtbondfut_i{2}.name,tc_govtbondfut_i{2}.table,...
    tc_govtbondfut_i{3}.name,tc_govtbondfut_i{3}.table,...
    tc_govtbondfut_i{4}.name,tc_govtbondfut_i{4}.table,...
    'breachuplvlup_tb',tb_govtbondfut_i{1}.table,...
    'breachdnlvldn_tb',tb_govtbondfut_i{2}.table,...
    'breachupsshighvalue_tb',tb_govtbondfut_i{3}.table,...
    'breachdnbshighvalue_tb',tb_govtbondfut_i{4}.table,...
    'breachuplvlup_tc',tb_govtbondfut_i{5}.table,...
    'breachdnlvldn_tc',tb_govtbondfut_i{6}.table,...
    'breachupsshighvalue_tc',tb_govtbondfut_i{7}.table,...
    'breachdnbshighvalue_tc',tb_govtbondfut_i{8}.table,...
    'kelly_matrix_l',KMat_L_govtbondfut_i,...
    'kelly_matrix_s',KMat_S_govtbondfut_i,...
    'winprob_matrix_l',WMat_L_govtbondfut_i,...
    'winprob_matrix_s',WMat_S_govtbondfut_i,...
    'signal_l',{signal_l_valid_govtbondfut},...
    'signal_s',{signal_s_valid_govtbondfut},...
    'asset_list',{assetlist_govtbondfut'});
%%
dir_ = [getenv('onedrive'),'\fractal backtest\kelly distribution\matlab\govtbondfut\'];
save([dir_,'strat_intraday_govtbondfut.mat'],'strat_intraday_govtbondfut');
fprintf('file saved...\n');
