names_pm = {'xau'};

output_daily_pm = fractal_kelly_summary('codes',names_pm,...
    'frequency','daily','usefractalupdate',0,'usefibonacci',1,'direction','both');
%%
[rp_tc_pm,rp_tb_pm,tbl_pm,k_l_pm,k_s_pm,tblbyasset_l_pm,tblbyasset_s_pm] = kellydistributionsummary(output_daily_pm);
%%
signal_l_valid_pm = k_l_pm.opensignal_unique_l(logical(k_l_pm.use_unique_l));
signal_s_valid_pm = k_s_pm.opensignal_unique_s(logical(k_s_pm.use_unique_s));
assetlist_pm = unique([tblbyasset_l_pm.assetlist;tblbyasset_s_pm.assetlist]);
nasset = size(assetlist_pm,1);
%
WMat_L = zeros(length(signal_l_valid_pm),nasset);
RMat_L = WMat_L;
KMat_L = WMat_L;
for i = 1:length(signal_l_valid_pm)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_daily_pm,'assetname',assetlist_pm{j},'direction','l','signalname',signal_l_valid_pm{i});
        WMat_L(i,j) = ret.W;
        RMat_L(i,j) = ret.R;
        KMat_L(i,j) = ret.K;
    end
end
%
WMat_S = zeros(length(signal_s_valid_pm),nasset);
RMat_S = WMat_S;
KMat_S = WMat_S;
for i = 1:length(signal_s_valid_pm)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_daily_pm,'assetname',assetlist_pm{j},'direction','s','signalname',signal_s_valid_pm{i});
        WMat_S(i,j) = ret.W;
        RMat_S(i,j) = ret.R;
        KMat_S(i,j) = ret.K;
    end
end
%%
strat_daily_pm = struct('tblbyasset_l',tblbyasset_l_pm,...
    'tblbyasset_s',tblbyasset_s_pm,...
    'kelly_table_l',k_l_pm,...
    'kelly_table_s',k_s_pm,...
    rp_tc_pm{1}.name,rp_tc_pm{1}.table,...
    rp_tc_pm{2}.name,rp_tc_pm{2}.table,...
    rp_tc_pm{3}.name,rp_tc_pm{3}.table,...
    rp_tc_pm{4}.name,rp_tc_pm{4}.table,...
    'breachuplvlup_tb',rp_tb_pm{1}.table,...
    'breachdnlvldn_tb',rp_tb_pm{2}.table,...
    'breachupsshighvalue_tb',rp_tb_pm{3}.table,...
    'breachdnbshighvalue_tb',rp_tb_pm{4}.table,...
    'breachuplvlup_tc',rp_tc_pm{5}.table,...
    'breachdnlvldn_tc',rp_tc_pm{6}.table,...
    'breachupsshighvalue_tc',rp_tc_pm{7}.table,...
    'breachdnbshighvalue_tc',rp_tc_pm{8}.table,...
    'breachuphighsc13',rp_tc_pm{9}.table,...
    'breachdnlowbc13',rp_tc_pm{10}.table,...
    'kelly_matrix_l',KMat_L,...
    'kelly_matrix_s',KMat_S,...
    'winprob_matrix_l',WMat_L,...
    'winprob_matrix_s',WMat_S,...
    'signal_l',{signal_l_valid_pm},...
    'signal_s',{signal_s_valid_pm},...
    'asset_list',{assetlist_pm'});
%%
[tbl_report_pm,stats_report_pm] = kellydistributionreport(tbl_pm,strat_daily_pm);
%%
output2_daily_pm = fractal_kelly_summary('codes',names_pm,...
    'frequency','daily','usefractalupdate',0,'usefibonacci',1,'direction','both',...
    'fromdate','2023-10-30');
%
[~,~,tbl2_pm,~,~,~,~] = kellydistributionsummary(output2_daily_pm,true);
tbl_report2_pm = kellydistributionreport(tbl2_pm,strat_daily_pm);
close all;
%%
code = 'xau';
dailybar_ = cDataFileIO.loadDataFromTxtFile([getenv('datapath'),'globalmacro\',code,'_daily.txt']);
[dailybarmat_,dailybarstruct_] = tools_technicalplot1(dailybar_,2,false);dailybarmat_(:,1) = x2mdate(dailybarmat_(:,1));
trade_ = fractal_latestposition('code',code,'extrainfo',dailybarstruct_,'usefractalupdate',0);
tools_technicalplot2(dailybarmat_(end-61:end,:),2,code,true,0.0001);
