%
output_govtbondyield = fractal_kelly_summary('codes',{'gzhy';'gzhy_30y'},'frequency','daily','usefractalupdate',0,'usefibonacci',1,'direction','both');
%%
[tc_govtbondyield,tb_govtbondyield,tbl_govtbondyield,k_l_govtbondyield,k_s_govtbondyield,tblbyasset_l_govtbondyield,tblbyasset_s_govtbondyield] = kellydistrubitionsummary(output_govtbondyield);
%%
signal_l_valid_govtbondyield = k_l_govtbondyield.opensignal_unique_l(logical(k_l_govtbondyield.use_unique_l));
signal_s_valid_govtbondyield = k_s_govtbondyield.opensignal_unique_s(logical(k_s_govtbondyield.use_unique_s));
assetlist_govtbondyield = unique([tblbyasset_l_govtbondyield.assetlist;tblbyasset_s_govtbondyield.assetlist]);
nasset = size(assetlist_govtbondyield,1);
%
WMat_L_govtbondyield = zeros(length(signal_l_valid_govtbondyield),nasset);
RMat_L_govtbondyield = WMat_L_govtbondyield;
KMat_L_govtbondyield = WMat_L_govtbondyield;
for i = 1:length(signal_l_valid_govtbondyield)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_govtbondyield,'assetname',assetlist_govtbondyield{j},'direction','l','signalname',signal_l_valid_govtbondyield{i});
        WMat_L_govtbondyield(i,j) = ret.W;
        RMat_L_govtbondyield(i,j) = ret.R;
        KMat_L_govtbondyield(i,j) = ret.K;
    end
end
%
WMat_S_govtbondyield = zeros(length(signal_s_valid_govtbondyield),nasset);
RMat_S_govtbondyield = WMat_S_govtbondyield;
KMat_S_govtbondyield = WMat_S_govtbondyield;
for i = 1:length(signal_s_valid_govtbondyield)
    for j = 1:nasset
        ret = kellyempirical('distribution',output_govtbondyield,'assetname',assetlist_govtbondyield{j},'direction','s','signalname',signal_s_valid_govtbondyield{i});
        WMat_S_govtbondyield(i,j) = ret.W;
        RMat_S_govtbondyield(i,j) = ret.R;
        KMat_S_govtbondyield(i,j) = ret.K;
    end
end
%
%%
strat_intraday_govtbondyield = struct('tblbyasset_l',tblbyasset_l_govtbondyield,...
    'tblbyasset_s',tblbyasset_s_govtbondyield,...
    'kelly_table_l',k_l_govtbondyield,...
    'kelly_table_s',k_s_govtbondyield,...
    tc_govtbondyield{1}.name,tc_govtbondyield{1}.table,...
    tc_govtbondyield{2}.name,tc_govtbondyield{2}.table,...
    tc_govtbondyield{3}.name,tc_govtbondyield{3}.table,...
    tc_govtbondyield{4}.name,tc_govtbondyield{4}.table,...
    'breachuplvlup_tb',tb_govtbondyield{1}.table,...
    'breachdnlvldn_tb',tb_govtbondyield{2}.table,...
    'breachupsshighvalue_tb',tb_govtbondyield{3}.table,...
    'breachdnbshighvalue_tb',tb_govtbondyield{4}.table,...
    'breachuplvlup_tc',tb_govtbondyield{5}.table,...
    'breachdnlvldn_tc',tb_govtbondyield{6}.table,...
    'breachupsshighvalue_tc',tb_govtbondyield{7}.table,...
    'breachdnbshighvalue_tc',tb_govtbondyield{8}.table,...
    'kelly_matrix_l',KMat_L_govtbondyield,...
    'kelly_matrix_s',KMat_S_govtbondyield,...
    'winprob_matrix_l',WMat_L_govtbondyield,...
    'winprob_matrix_s',WMat_S_govtbondyield,...
    'signal_l',{signal_l_valid_govtbondyield},...
    'signal_s',{signal_s_valid_govtbondyield},...
    'asset_list',{assetlist_govtbondyield'});
%%
dir_ = [getenv('onedrive'),'\fractal backtest\kelly distribution\matlab\govtbondyield\'];
save([dir_,'strat_daily_govtbondyield.mat'],'strat_daily_govtbondyield');
fprintf('file saved...\n');
