ui = struct('guiW',1728,'guiH',972,'guiX',10,'guiY',41,...
    'guiColor',[0.85 0.85 0.85],...
    'guiName','CTP MDEFUT',...
    'panel2LeftFrame',0.01,...     
    'panel2RightFrame',0.01,...
    'panel2TopFrame',0.02,...
    'panel2BottomFrame',0.02,...
    'panel2panelH',0.01,...
    'panel2panelV',0.01,...
    'panelFontSize', 9,...
    'topLeftBlockW',0.18,...
    'topPanelH',0.2);
close all;
%%
close all;
handles = gui_frame_md_init(ui);
%general setup
generalsetup_propnames = {'CTPCounter';'UseHistData';'ConfigFile';...
    'Mode';'ReplayTimeStart';'ReplayTimeEnd'};
generalsetup_propvalues = {{'ccb_ly_fut','ccb_yy_fut','citic_kim_fut'};...
    {'yes','no'};{'gui_mdefut_config1.txt'};{'realtime';'replay'};{'yyyy-mm-dd'};{'yyyy-mm-dd'}};
handles = gui_frame_generalsetup(handles,ui_frame,generalsetup_propnames,generalsetup_propvalues);
%%
%market data
handles = gui_frame_mktdatatbl(handles,ui_frame);