function [] = settimer(monitorbase)
    timername = ['timer-',class(monitorbase)];
    timertag = ['tag-',class(monitorbase)];
    timertofind = timerfind('Name',timername);
    if isempty(monitorbase.timer_) || isempty(timertofind)
        monitorbase.timer_ = timer('Period', monitorbase.timer_interval_,...
            'StartFcn',@monitorbase.start_timer_fcn,...
            'TimerFcn', @monitorbase.replay_timer_fcn,...
            'StopFcn',@monitorbase.stop_timer_fcn,...
            'BusyMode', 'drop',...
            'ExecutionMode', 'fixedSpacing',...
            'StartDelay', min(monitorbase.timer_interval_,5),...
            'Name',timername,...
            'Tag',timertag);
    end
end
%end of settimer