function flag = isobjtype(type)
    %function to check whether input "type" is an appropirate object type
    if ~ischar(type)
        error('isobjtype:invalid input, string required!')
    end
    
    if ~(strcmpi('DICTIONARY',type) ||...
            strcmpi('MODEL',type) ||...
            strcmpi('YIELDCURVE',type) ||...
            strcmpi('MKTDATA',type) ||...
            strcmpi('VOL',type) ||...
            strcmpi('SECURITY',type) ||...
            strcmpi('BOOK',type) ||...
            strcmpi('EXTRAINFO',type) ||...
            strcmpi('RESULTS',type))
        flag = 0;
    else
        flag = 1;
    end
    
end