function [] = print(obj)
%cQuoteFut
    if ~obj.bond_flag
        fprintf('%s trade:%s;bid:%s;ask:%s;instrument:%s;\n',obj.update_time2,...
            num2str(obj.last_trade),...
            num2str(obj.bid1),...
            num2str(obj.ask1),...
            obj.code_ctp);
    else
        fprintf('%s trade:%4.3f;bid:%4.3f;ask:%4.3f;yield:%4.2f;duration:%2.1f;instrument:%s;\n',obj.update_time2,...
            obj.last_trade,...
            obj.bid1,...
            obj.ask1,...
            obj.yield_last_trade,...
            obj.duration,...
            obj.code_ctp);
    end
end